// This file is auto-generated by the @tanstack/router-plugin Vite plugin on
// `vite dev` / `vite build`. The stub here keeps `tsc --noEmit` happy before
// the first build. Do not edit manually — it'll be overwritten.

export const routeTree = {} as any;
