/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VideosVideoIdRouteImport } from './routes/videos.$videoId'
import { Route as ApiCronPollRouteImport } from './routes/api/cron/poll'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosVideoIdRoute = VideosVideoIdRouteImport.update({
  id: '/videos/$videoId',
  path: '/videos/$videoId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronPollRoute = ApiCronPollRouteImport.update({
  id: '/api/cron/poll',
  path: '/api/cron/poll',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/videos/$videoId': typeof VideosVideoIdRoute
  '/api/cron/poll': typeof ApiCronPollRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/videos/$videoId': typeof VideosVideoIdRoute
  '/api/cron/poll': typeof ApiCronPollRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/videos/$videoId': typeof VideosVideoIdRoute
  '/api/cron/poll': typeof ApiCronPollRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/videos/$videoId' | '/api/cron/poll'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/videos/$videoId' | '/api/cron/poll'
  id: '__root__' | '/' | '/videos/$videoId' | '/api/cron/poll'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VideosVideoIdRoute: typeof VideosVideoIdRoute
  ApiCronPollRoute: typeof ApiCronPollRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/$videoId': {
      id: '/videos/$videoId'
      path: '/videos/$videoId'
      fullPath: '/videos/$videoId'
      preLoaderRoute: typeof VideosVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/poll': {
      id: '/api/cron/poll'
      path: '/api/cron/poll'
      fullPath: '/api/cron/poll'
      preLoaderRoute: typeof ApiCronPollRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VideosVideoIdRoute: VideosVideoIdRoute,
  ApiCronPollRoute: ApiCronPollRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
